// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"context"
)

type Querier interface {
	CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error)
	CreateOrderProduct(ctx context.Context, arg CreateOrderProductParams) (OrderProduct, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateUserToUser(ctx context.Context, arg CreateUserToUserParams) (UserToUser, error)
	DeleteOrder(ctx context.Context, uuid int64) (int64, error)
	DeleteProduct(ctx context.Context, uuid int64) (int64, error)
	DeleteUser(ctx context.Context, uuid int64) (int64, error)
	GetOrder(ctx context.Context, uuid int64) (Order, error)
	GetOrderProduct(ctx context.Context, arg GetOrderProductParams) (OrderProduct, error)
	GetProduct(ctx context.Context, uuid int64) (Product, error)
	GetProductForUpdate(ctx context.Context, uuid int64) (Product, error)
	GetUser(ctx context.Context, uuid int64) (User, error)
	// This will allow us to block transactions till the end of commit
	GetUserForUpdate(ctx context.Context, uuid int64) (User, error)
	GetUserToUser(ctx context.Context, arg GetUserToUserParams) (UserToUser, error)
	ListOrderProducts(ctx context.Context, arg ListOrderProductsParams) ([]OrderProduct, error)
	ListOrders(ctx context.Context, arg ListOrdersParams) ([]Order, error)
	ListProducts(ctx context.Context, arg ListProductsParams) ([]Product, error)
	ListUserToUser(ctx context.Context, arg ListUserToUserParams) ([]UserToUser, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	ReduceProductInStock(ctx context.Context, arg ReduceProductInStockParams) (Product, error)
	ReduceUserBalance(ctx context.Context, arg ReduceUserBalanceParams) (User, error)
	UpdateOrder(ctx context.Context, arg UpdateOrderParams) (Order, error)
	UpdateOrderProduct(ctx context.Context, arg UpdateOrderProductParams) (OrderProduct, error)
	UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserToUser(ctx context.Context, arg UpdateUserToUserParams) (UserToUser, error)
}

var _ Querier = (*Queries)(nil)
