// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: user.sql

package db

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO "User" (
	"FirstName", 
	"MiddleName", 
	"LastName", 
	"Gender", 
	"Age") 
VALUES (
    $1, $2, $3, $4, $5
)
RETURNING "Uuid", "FirstName", "MiddleName", "LastName", "FullName", "Gender", "Age"
`

type CreateUserParams struct {
	FirstName  string `json:"FirstName"`
	MiddleName string `json:"MiddleName"`
	LastName   string `json:"LastName"`
	Gender     string `json:"Gender"`
	Age        int16  `json:"Age"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.FirstName,
		arg.MiddleName,
		arg.LastName,
		arg.Gender,
		arg.Age,
	)
	var i User
	err := row.Scan(
		&i.Uuid,
		&i.FirstName,
		&i.MiddleName,
		&i.LastName,
		&i.FullName,
		&i.Gender,
		&i.Age,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM "User"
WHERE "Uuid" = $1
`

func (q *Queries) DeleteUser(ctx context.Context, uuid int64) error {
	_, err := q.db.ExecContext(ctx, deleteUser, uuid)
	return err
}

const getUser = `-- name: GetUser :one
SELECT "Uuid", "FirstName", "MiddleName", "LastName", "FullName", "Gender", "Age" FROM "User"
WHERE "Uuid" = $1 LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, uuid int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, uuid)
	var i User
	err := row.Scan(
		&i.Uuid,
		&i.FirstName,
		&i.MiddleName,
		&i.LastName,
		&i.FullName,
		&i.Gender,
		&i.Age,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT "Uuid", "FirstName", "MiddleName", "LastName", "FullName", "Gender", "Age" FROM "User"
ORDER BY "FullName"
LIMIT $1
OFFSET $2
`

type ListUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.Uuid,
			&i.FirstName,
			&i.MiddleName,
			&i.LastName,
			&i.FullName,
			&i.Gender,
			&i.Age,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserAge = `-- name: UpdateUserAge :one
UPDATE "User"
  set "Age" = $2
WHERE "Uuid" = $1
RETURNING "Uuid", "FirstName", "MiddleName", "LastName", "FullName", "Gender", "Age"
`

type UpdateUserAgeParams struct {
	Uuid int64 `json:"Uuid"`
	Age  int16 `json:"Age"`
}

func (q *Queries) UpdateUserAge(ctx context.Context, arg UpdateUserAgeParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserAge, arg.Uuid, arg.Age)
	var i User
	err := row.Scan(
		&i.Uuid,
		&i.FirstName,
		&i.MiddleName,
		&i.LastName,
		&i.FullName,
		&i.Gender,
		&i.Age,
	)
	return i, err
}

const updateUserFirstName = `-- name: UpdateUserFirstName :one
UPDATE "User"
  set "FirstName" = $2
WHERE "Uuid" = $1
RETURNING "Uuid", "FirstName", "MiddleName", "LastName", "FullName", "Gender", "Age"
`

type UpdateUserFirstNameParams struct {
	Uuid      int64  `json:"Uuid"`
	FirstName string `json:"FirstName"`
}

func (q *Queries) UpdateUserFirstName(ctx context.Context, arg UpdateUserFirstNameParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserFirstName, arg.Uuid, arg.FirstName)
	var i User
	err := row.Scan(
		&i.Uuid,
		&i.FirstName,
		&i.MiddleName,
		&i.LastName,
		&i.FullName,
		&i.Gender,
		&i.Age,
	)
	return i, err
}

const updateUserGender = `-- name: UpdateUserGender :one
UPDATE "User"
  set "Gender" = $2
WHERE "Uuid" = $1
RETURNING "Uuid", "FirstName", "MiddleName", "LastName", "FullName", "Gender", "Age"
`

type UpdateUserGenderParams struct {
	Uuid   int64  `json:"Uuid"`
	Gender string `json:"Gender"`
}

func (q *Queries) UpdateUserGender(ctx context.Context, arg UpdateUserGenderParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserGender, arg.Uuid, arg.Gender)
	var i User
	err := row.Scan(
		&i.Uuid,
		&i.FirstName,
		&i.MiddleName,
		&i.LastName,
		&i.FullName,
		&i.Gender,
		&i.Age,
	)
	return i, err
}

const updateUserLastName = `-- name: UpdateUserLastName :one
UPDATE "User"
  set "LastName" = $2
WHERE "Uuid" = $1
RETURNING "Uuid", "FirstName", "MiddleName", "LastName", "FullName", "Gender", "Age"
`

type UpdateUserLastNameParams struct {
	Uuid     int64  `json:"Uuid"`
	LastName string `json:"LastName"`
}

func (q *Queries) UpdateUserLastName(ctx context.Context, arg UpdateUserLastNameParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserLastName, arg.Uuid, arg.LastName)
	var i User
	err := row.Scan(
		&i.Uuid,
		&i.FirstName,
		&i.MiddleName,
		&i.LastName,
		&i.FullName,
		&i.Gender,
		&i.Age,
	)
	return i, err
}

const updateUserMiddleName = `-- name: UpdateUserMiddleName :one
UPDATE "User"
  set "MiddleName" = $2
WHERE "Uuid" = $1
RETURNING "Uuid", "FirstName", "MiddleName", "LastName", "FullName", "Gender", "Age"
`

type UpdateUserMiddleNameParams struct {
	Uuid       int64  `json:"Uuid"`
	MiddleName string `json:"MiddleName"`
}

func (q *Queries) UpdateUserMiddleName(ctx context.Context, arg UpdateUserMiddleNameParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserMiddleName, arg.Uuid, arg.MiddleName)
	var i User
	err := row.Scan(
		&i.Uuid,
		&i.FirstName,
		&i.MiddleName,
		&i.LastName,
		&i.FullName,
		&i.Gender,
		&i.Age,
	)
	return i, err
}
